// ramos.js
export const ramos = [
  // Semestre 1
  {
    id: "biologia-celular-molecular-1",
    nombre: "Biología Celular y Molecular",
    semestre: 1,
    tipo: "anual",
    creditos: 10,
    requisitos: [],
    nota: null,
  },
  {
    id: "integracion-i-1",
    nombre: "Integración I",
    semestre: 1,
    tipo: "anual",
    creditos: 5,
    requisitos: [],
    nota: null,
  },
  {
    id: "fundamentos-teologia",
    nombre: "Fundamentos de la Teología",
    semestre: 1,
    tipo: "anual",
    creditos: 4,
    requisitos: [],
    nota: null,
  },
  {
    id: "fundamentos-filosofia",
    nombre: "Fundamentos de la Filosofía",
    semestre: 1,
    tipo: "anual",
    creditos: 4,
    requisitos: [],
    nota: null,
  },
  {
    id: "morfologia-humana",
    nombre: "Morfología Humana",
    semestre: 1,
    tipo: "anual",
    creditos: 12,
    requisitos: [],
    nota: null,
  },
  {
    id: "biomatematicas",
    nombre: "Biomatemáticas",
    semestre: 1,
    tipo: "semestral",
    creditos: 3,
    requisitos: [],
    nota: 62,
  },
  {
    id: "introduccion-comunicacion-medica",
    nombre: "Introducción a la Comunicación Médica",
    semestre: 1,
    tipo: "semestral",
    creditos: 2,
    requisitos: [],
    nota: 69,
  },
  {
    id: "quimica",
    nombre: "Química",
    semestre: 1,
    tipo: "semestral",
    creditos: 5,
    requisitos: [],
    nota: 58,
  },
  {
    id: "lecturas-ingles",
    nombre: "Lecturas Textos Médicos en Inglés",
    semestre: 1,
    tipo: "semestral",
    creditos: 2,
    requisitos: [],
    nota: 70,
  },

  // Semestre 2
  {
    id: "biologia-celular-molecular-2",
    nombre: "Biología Celular y Molecular",
    semestre: 2,
    tipo: "anual",
    creditos: 10,
    requisitos: [],
    nota: 52,
  },
  {
    id: "integracion-i-2",
    nombre: "Integración I",
    semestre: 2,
    tipo: "anual",
    creditos: 5,
    requisitos: [],
    nota: 70,
  },
  {
    id: "fundamentos-teologia-2",
    nombre: "Fundamentos de la Teología",
    semestre: 2,
    tipo: "anual",
    creditos: 4,
    requisitos: [],
    nota: 66,
  },
  {
    id: "fundamentos-filosofia-2",
    nombre: "Fundamentos de la Filosofía",
    semestre: 2,
    tipo: "anual",
    creditos: 4,
    requisitos: [],
    nota: 68,
  },
  {
    id: "morfologia-humana-2",
    nombre: "Morfología Humana",
    semestre: 2,
    tipo: "anual",
    creditos: 12,
    requisitos: [],
    nota: 56,
  },
  {
    id: "bioquimica-i",
    nombre: "Bioquímica I",
    semestre: 2,
    tipo: "semestral",
    creditos: 4,
    requisitos: [],
    nota: 55,
  },
  {
    id: "biofisica",
    nombre: "Biofísica",
    semestre: 2,
    tipo: "semestral",
    creditos: 3,
    requisitos: [],
    nota: 65,
  },
  {
    id: "introduccion-medicina",
    nombre: "Introducción a la Medicina",
    semestre: 2,
    tipo: "semestral",
    creditos: 2,
    requisitos: [],
    nota: 68,
  },
  {
    id: "bioestadistica",
    nombre: "Bioestadística",
    semestre: 2,
    tipo: "semestral",
    creditos: 4,
    requisitos: ["biomatematicas"],
    nota: 70,
  },

  // Semestre 3
  {
    id: "fisiologia-1",
    nombre: "Fisiología",
    semestre: 3,
    tipo: "anual",
    creditos: 8,
    requisitos: [
      "morfologia-humana",
      "biologia-celular-molecular-2",
      "bioquimica-i",
      "biofisica",
    ],
    nota: null,
  },
  {
    id: "integracion-ii-1",
    nombre: "Integración II",
    semestre: 3,
    tipo: "anual",
    creditos: 5,
    requisitos: ["integracion-i-2"],
    nota: null,
  },
  {
    id: "antropologia-medica-1",
    nombre: "Antropología Médica",
    semestre: 3,
    tipo: "anual",
    creditos: 4,
    requisitos: ["fundamentos-filosofia-2", "fundamentos-teologia-2"],
    nota: null,
  },
  {
    id: "microbiologia-1",
    nombre: "Microbiología",
    semestre: 3,
    tipo: "anual",
    creditos: 7,
    requisitos: ["biologia-celular-molecular-2", "bioquimica-i"],
    nota: null,
  },
  {
    id: "atencion-primaria-salud",
    nombre: "Atención Primaria en Salud",
    semestre: 3,
    tipo: "anual",
    creditos: 4,
    requisitos: ["introduccion-comunicacion-medica"],
    nota: null,
  },
  {
    id: "histologia",
    nombre: "Histología",
    semestre: 3,
    tipo: "semestral",
    creditos: 5,
    requisitos: ["morfologia-humana", "biologia-celular-molecular-2"],
    nota: 62,
  },
  {
    id: "neurociencia",
    nombre: "Neurociencia",
    semestre: 3,
    tipo: "semestral",
    creditos: 3,
    requisitos: ["morfologia-humana"],
    nota: 53,
  },
  {
    id: "bioquimica-ii",
    nombre: "Bioquímica II",
    semestre: 3,
    tipo: "semestral",
    creditos: 5,
    requisitos: ["bioquimica-i"],
    nota: 51,
  },
  {
    id: "metodologia-investigacion",
    nombre: "Metodología de la Investigación",
    semestre: 3,
    tipo: "semestral",
    creditos: 3,
    requisitos: ["bioestadistica"],
    nota: 70,
  },

  // Semestre 4
  {
    id: "fisiologia-2",
    nombre: "Fisiología",
    semestre: 4,
    tipo: "anual",
    creditos: 8,
    requisitos: [],
    nota: null,
  },
  {
    id: "integracion-ii-2",
    nombre: "Integración II",
    semestre: 4,
    tipo: "anual",
    creditos: 5,
    requisitos: [],
    nota: null,
  },
  {
    id: "antropologia-medica-2",
    nombre: "Antropología Médica",
    semestre: 4,
    tipo: "anual",
    creditos: 4,
    requisitos: [],
    nota: null,
  },
  {
    id: "microbiologia-2",
    nombre: "Microbiología",
    semestre: 4,
    tipo: "anual",
    creditos: 7,
    requisitos: [],
    nota: null,
  },
  {
    id: "atencion-primaria-salud-2",
    nombre: "Atención Primaria en Salud",
    semestre: 4,
    tipo: "anual",
    creditos: 4,
    requisitos: [],
    nota: null,
  },
  {
    id: "integracion-del-saber-4",
    nombre: "Integración del Saber",
    semestre: 4,
    tipo: "semestral",
    creditos: 2,
    requisitos: [],
    nota: null,
  },
  {
    id: "epidemiologia",
    nombre: "Epidemiología",
    semestre: 4,
    tipo: "semestral",
    creditos: 4,
    requisitos: ["metodologia-investigacion"],
    nota: null,
  },
  {
    id: "farmacologia",
    nombre: "Farmacología",
    semestre: 4,
    tipo: "semestral",
    creditos: 4,
    requisitos: ["bioquimica-ii"],
    nota: null,
  },
  {
    id: "inmunologia",
    nombre: "Inmunología",
    semestre: 4,
    tipo: "semestral",
    creditos: 2,
    requisitos: ["histologia", "bioquimica-ii"],
    nota: null,
  },

  // Semestre 5
  {
    id: "integracion-iii-5",
    nombre: "Integración III",
    semestre: 5,
    tipo: "anual",
    creditos: 5,
    requisitos: ["integracion-ii-2"],
    nota: null,
  },
  {
    id: "salud-publica-gestion",
    nombre: "Salud Pública y Gestión",
    semestre: 5,
    tipo: "anual",
    creditos: 6,
    requisitos: ["epidemiologia"],
    nota: null,
  },
  {
    id: "fisiopatologia",
    nombre: "Fisiopatología",
    semestre: 5,
    tipo: "anual",
    creditos: 10,
    requisitos: [
      "fisiologia-1",
      "bioquimica-ii",
      "neurociencia",
      "histologia",
    ],
    nota: null,
  },
  {
    id: "fundamentos-accion-medica",
    nombre: "Fundamentos de la Acción Médica",
    semestre: 5,
    tipo: "anual",
    creditos: 4,
    requisitos: ["antropologia-medica-1"],
    nota: null,
  },
  {
    id: "semiologia",
    nombre: "Semiología",
    semestre: 5,
    tipo: "semestral",
    creditos: 12,
    requisitos: ["fisiologia-1", "histologia"],
    nota: null,
  },
  {
    id: "patologia-general",
    nombre: "Patología General",
    semestre: 5,
    tipo: "semestral",
    creditos: 4,
    requisitos: ["fisiologia-1", "histologia"],
    nota: null,
  },
  {
    id: "optativo-profundizacion-5",
    nombre: "Optativo de Profundización",
    semestre: 5,
    tipo: "semestral",
    creditos: 2,
    requisitos: [],
    nota: null,
  },

  // Semestre 6
  {
    id: "integracion-iii-6",
    nombre: "Integración III",
    semestre: 6,
    tipo: "anual",
    creditos: 5,
    requisitos: ["integracion-ii-2"],
    nota: null,
  },
  {
    id: "salud-publica-gestion-6",
    nombre: "Salud Pública y Gestión",
    semestre: 6,
    tipo: "anual",
    creditos: 6,
    requisitos: ["epidemiologia"],
    nota: null,
  },
  {
    id: "fisiopatologia-6",
    nombre: "Fisiopatología",
    semestre: 6,
    tipo: "anual",
    creditos: 10,
    requisitos: [
      "fisiologia-1",
      "bioquimica-ii",
      "neurociencia",
      "histologia",
    ],
    nota: null,
  },
  {
    id: "fundamentos-accion-medica-6",
    nombre: "Fundamentos de la Acción Médica",
    semestre: 6,
    tipo: "anual",
    creditos: 4,
    requisitos: ["antropologia-medica-1"],
    nota: null,
  },
  {
    id: "anatomia-patologica",
    nombre: "Anatomía Patológica",
    semestre: 6,
    tipo: "semestral",
    creditos: 4,
    requisitos: ["patologia-general"],
    nota: null,
  },
  {
    id: "medicina-integrada-i",
    nombre: "Medicina Integrada I",
    semestre: 6,
    tipo: "semestral",
    creditos: 12,
    requisitos: ["semiologia", "microbiologia-1", "farmacologia"],
    nota: null,
  },
  {
    id: "patologia-quirurgica",
    nombre: "Patología Quirúrgica",
    semestre: 6,
    tipo: "semestral",
    creditos: 4,
    requisitos: ["patologia-general", "semiologia"],
    nota: null,
  },
  {
    id: "integracion-del-saber-6",
    nombre: "Integración del Saber",
    semestre: 6,
    tipo: "semestral",
    creditos: 2,
    requisitos: [],
    nota: null,
  },

  // Semestre 7
  {
    id: "ciencias-basicas-aplicadas-7",
    nombre: "Ciencias Básicas Aplicadas",
    semestre: 7,
    tipo: "anual",
    creditos: 7,
    requisitos: ["fisiopatologia", "farmacologia", "inmunologia", "microbiologia-2"],
    nota: null,
  },
  {
    id: "proyecto-investigacion",
    nombre: "Proyecto de Investigación",
    semestre: 7,
    tipo: "anual",
    creditos: 4,
    requisitos: ["salud-publica-gestion"],
    nota: null,
  },
  {
    id: "cirugia",
    nombre: "Cirugía",
    semestre: 7,
    tipo: "anual",
    creditos: 17,
    requisitos: ["patologia-quirurgica", "fisiopatologia"],
    nota: null,
  },
  {
    id: "bioetica-general",
    nombre: "Bioética General",
    semestre: 7,
    tipo: "anual",
    creditos: 4,
    requisitos: ["fundamentos-accion-medica"],
    nota: null,
  },
  {
    id: "geriatria-cuidados",
    nombre: "Geriatría y Cuidados en Situaciones Especiales",
    semestre: 7,
    tipo: "anual",
    creditos: 4,
    requisitos: ["medicina-integrada-i", "fisiopatologia"],
    nota: null,
  },
  {
    id: "medicina-integrada-ii",
    nombre: "Medicina Integrada II",
    semestre: 7,
    tipo: "anual",
    creditos: 22,
    requisitos: ["medicina-integrada-i", "fisiopatologia"],
    nota: null,
  },
  {
    id: "integracion-iv",
    nombre: "Integración IV",
    semestre: 7,
    tipo: "anual",
    creditos: 5,
    requisitos: ["integracion-iii-5"],
    nota: null,
  },
  {
    id: "optativo-profundizacion-7",
    nombre: "Optativo de Profundización",
    semestre: 7,
    tipo: "semestral",
    creditos: 2,
    requisitos: [],
    nota: null,
  },

  // Semestre 8
  {
    id: "ciencias-basicas-aplicadas-8",
    nombre: "Ciencias Básicas Aplicadas",
    semestre: 8,
    tipo: "anual",
    creditos: 7,
    requisitos: ["fisiopatologia", "farmacologia", "inmunologia", "microbiologia-2"],
    nota: null,
  },
  {
    id: "proyecto-investigacion-8",
    nombre: "Proyecto de Investigación",
    semestre: 8,
    tipo: "anual",
    creditos: 4,
    requisitos: ["salud-publica-gestion"],
    nota: null,
  },
  {
    id: "cirugia-8",
    nombre: "Cirugía",
    semestre: 8,
    tipo: "anual",
    creditos: 17,
    requisitos: ["patologia-quirurgica", "fisiopatologia"],
    nota: null,
  },
  {
    id: "bioetica-general-8",
    nombre: "Bioética General",
    semestre: 8,
    tipo: "anual",
    creditos: 4,
    requisitos: ["fundamentos-accion-medica"],
    nota: null,
  },
  {
    id: "geriatria-cuidados-8",
    nombre: "Geriatría y Cuidados en Situaciones Especiales",
    semestre: 8,
    tipo: "anual",
    creditos: 4,
    requisitos: ["medicina-integrada-i", "fisiopatologia"],
    nota: null,
  },
  {
    id: "medicina-integrada-ii-8",
    nombre: "Medicina Integrada II",
    semestre: 8,
    tipo: "anual",
    creditos: 22,
    requisitos: ["medicina-integrada-i", "fisiopatologia"],
    nota: null,
  },
  {
    id: "integracion-iv-8",
    nombre: "Integración IV",
    semestre: 8,
    tipo: "anual",
    creditos: 5,
    requisitos: ["integracion-iii-5"],
    nota: null,
  },
  {
    id: "integracion-del-saber-8",
    nombre: "Integración del Saber",
    semestre: 8,
    tipo: "semestral",
    creditos: 2,
    requisitos: [],
    nota: null,
  },

  // Semestre 9
  {
    id: "obstetricia-ginecologia",
    nombre: "Obstetricia y Ginecología",
    semestre: 9,
    tipo: "anual",
    creditos: 12,
    requisitos: ["medicina-integrada-ii", "patologia-general", "anatomia-patologica"],
    nota: null,
  },
  {
    id: "pediatria-cirugia-infantil",
    nombre: "Pediatría y Cirugía Infantil",
    semestre: 9,
    tipo: "anual",
    creditos: 12,
    requisitos: ["medicina-integrada-ii", "patologia-general", "anatomia-patologica"],
    nota: null,
  },
  {
    id: "psiquiatria-psicopatologia",
    nombre: "Psiquiatría y Psicopatología",
    semestre: 9,
    tipo: "anual",
    creditos: 5,
    requisitos: ["medicina-integrada-ii", "neurociencia"],
    nota: null,
  },
  {
    id: "bioetica-especial",
    nombre: "Bioética Especial",
    semestre: 9,
    tipo: "anual",
    creditos: 4,
    requisitos: ["bioetica-general"],
    nota: null,
  },
  {
    id: "integracion-v",
    nombre: "Integración V",
    semestre: 9,
    tipo: "anual",
    creditos: 4,
    requisitos: ["integracion-iv"],
    nota: null,
  },
  {
    id: "neurociencia-neurocirugia",
    nombre: "Neurociencia y Neurocirugía",
    semestre: 9,
    tipo: "anual",
    creditos: 5,
    requisitos: ["neurociencia", "medicina-integrada-ii", "patologia-general", "anatomia-patologica"],
    nota: null,
  },
  {
    id: "especialidades-medico-quirurgicas",
    nombre: "Especialidades Médico-Quirúrgicas",
    semestre: 9,
    tipo: "anual",
    creditos: 8,
    requisitos: ["medicina-integrada-ii", "patologia-general", "anatomia-patologica"],
    nota: null,
  },
  {
    id: "integracion-del-saber-9",
    nombre: "Integración del Saber",
    semestre: 9,
    tipo: "semestral",
    creditos: 2,
    requisitos: [],
    nota: null,
  },

  // Semestre 10
  {
    id: "obstetricia-ginecologia-10",
    nombre: "Obstetricia y Ginecología",
    semestre: 10,
    tipo: "anual",
    creditos: 12,
    requisitos: [],
    nota: null,
  },
  {
    id: "pediatria-cirugia-infantil-10",
    nombre: "Pediatría y Cirugía Infantil",
    semestre: 10,
    tipo: "anual",
    creditos: 12,
    requisitos: [],
    nota: null,
  },
  {
    id: "psiquiatria-psicopatologia-10",
    nombre: "Psiquiatría y Psicopatología",
    semestre: 10,
    tipo: "anual",
    creditos: 5,
    requisitos: [],
    nota: null,
  },
  {
    id: "bioetica-especial-10",
    nombre: "Bioética Especial",
    semestre: 10,
    tipo: "anual",
    creditos: 4,
    requisitos: [],
    nota: null,
  },
  {
    id: "integracion-v-10",
    nombre: "Integración V",
    semestre: 10,
    tipo: "anual",
    creditos: 4,
    requisitos: [],
    nota: null,
  },
  {
    id: "neurociencia-neurocirugia-10",
    nombre: "Neurociencia y Neurocirugía",
    semestre: 10,
    tipo: "anual",
    creditos: 5,
    requisitos: [],
    nota: null,
  },
  {
    id: "especialidades-medico-quirurgicas-10",
    nombre: "Especialidades Médico-Quirúrgicas",
    semestre: 10,
    tipo: "anual",
    creditos: 8,
    requisitos: [],
    nota: null,
  },
  {
    id: "optativo-profundizacion-10",
    nombre: "Optativo de Profundización",
    semestre: 10,
    tipo: "semestral",
    creditos: 2,
    requisitos: [],
    nota: null,
  },
  {
    id: "medicina-legal",
    nombre: "Medicina Legal",
    semestre: 10,
    tipo: "semestral",
    creditos: 2,
    requisitos: ["anatomia-patologica", "bioetica-general"],
    nota: null,
  },

  // Semestre 11
  {
    id: "internado-medicina-interna-11",
    nombre: "Internado de Medicina Interna",
    semestre: 11,
    tipo: "anual",
    creditos: 48,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-cirugia-11",
    nombre: "Internado de Cirugía",
    semestre: 11,
    tipo: "anual",
    creditos: 24,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-medicina-familiar-comunitaria-11",
    nombre: "Internado de Medicina Familiar y Comunitaria",
    semestre: 11,
    tipo: "anual",
    creditos: 15,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-pediatria-cirugia-infantil-11",
    nombre: "Internado de Pediatría y Cirugía Infantil",
    semestre: 11,
    tipo: "anual",
    creditos: 24,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-obstetricia-ginecologia-11",
    nombre: "Internado de Obstetricia y Ginecología",
    semestre: 11,
    tipo: "anual",
    creditos: 24,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-especialidad-11",
    nombre: "Internado de Especialidad",
    semestre: 11,
    tipo: "anual",
    creditos: 35,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "practico-bioetica-clinica-i",
    nombre: "Práctico de Bioética Clínica I",
    semestre: 11,
    tipo: "semestral",
    creditos: 4,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },

  // Semestre 12
  {
    id: "internado-medicina-interna-12",
    nombre: "Internado de Medicina Interna",
    semestre: 12,
    tipo: "anual",
    creditos: 48,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-cirugia-12",
    nombre: "Internado de Cirugía",
    semestre: 12,
    tipo: "anual",
    creditos: 24,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-medicina-familiar-comunitaria-12",
    nombre: "Internado de Medicina Familiar y Comunitaria",
    semestre: 12,
    tipo: "anual",
    creditos: 15,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-pediatria-cirugia-infantil-12",
    nombre: "Internado de Pediatría y Cirugía Infantil",
    semestre: 12,
    tipo: "anual",
    creditos: 24,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-obstetricia-ginecologia-12",
    nombre: "Internado de Obstetricia y Ginecología",
    semestre: 12,
    tipo: "anual",
    creditos: 24,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-especialidad-12",
    nombre: "Internado de Especialidad",
    semestre: 12,
    tipo: "anual",
    creditos: 35,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "practico-bioetica-clinica-i-12",
    nombre: "Práctico de Bioética Clínica I",
    semestre: 12,
    tipo: "semestral",
    creditos: 4,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },

  // Semestre 13
  {
    id: "internado-medicina-interna-13",
    nombre: "Internado de Medicina Interna",
    semestre: 13,
    tipo: "anual",
    creditos: 48,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-cirugia-13",
    nombre: "Internado de Cirugía",
    semestre: 13,
    tipo: "anual",
    creditos: 24,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-medicina-familiar-comunitaria-13",
    nombre: "Internado de Medicina Familiar y Comunitaria",
    semestre: 13,
    tipo: "anual",
    creditos: 15,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-pediatria-cirugia-infantil-13",
    nombre: "Internado de Pediatría y Cirugía Infantil",
    semestre: 13,
    tipo: "anual",
    creditos: 24,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-obstetricia-ginecologia-13",
    nombre: "Internado de Obstetricia y Ginecología",
    semestre: 13,
    tipo: "anual",
    creditos: 24,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-especialidad-13",
    nombre: "Internado de Especialidad",
    semestre: 13,
    tipo: "anual",
    creditos: 35,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "practico-bioetica-clinica-ii",
    nombre: "Práctico de Bioética Clínica II",
    semestre: 13,
    tipo: "semestral",
    creditos: 4,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },

  // Semestre 14
  {
    id: "internado-medicina-interna-14",
    nombre: "Internado de Medicina Interna",
    semestre: 14,
    tipo: "anual",
    creditos: 48,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-cirugia-14",
    nombre: "Internado de Cirugía",
    semestre: 14,
    tipo: "anual",
    creditos: 24,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-medicina-familiar-comunitaria-14",
    nombre: "Internado de Medicina Familiar y Comunitaria",
    semestre: 14,
    tipo: "anual",
    creditos: 15,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-pediatria-cirugia-infantil-14",
    nombre: "Internado de Pediatría y Cirugía Infantil",
    semestre: 14,
    tipo: "anual",
    creditos: 24,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-obstetricia-ginecologia-14",
    nombre: "Internado de Obstetricia y Ginecología",
    semestre: 14,
    tipo: "anual",
    creditos: 24,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "internado-especialidad-14",
    nombre: "Internado de Especialidad",
    semestre: 14,
    tipo: "anual",
    creditos: 35,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },
  {
    id: "practico-bioetica-clinica-ii-14",
    nombre: "Práctico de Bioética Clínica II",
    semestre: 14,
    tipo: "semestral",
    creditos: 4,
    requisitos: ["aprobacion-licenciatura"],
    nota: null,
  },

  // Requisito especial para internados y prácticos:
  {
    id: "aprobacion-licenciatura",
    nombre: "Aprobación de todos los créditos de Licenciatura",
    semestre: null,
    tipo: null,
    creditos: null,
    requisitos: [],
    nota: null,
  },
];
